version: '3.7'

services:
  handler:
    image: sergienkoandrew/mqhandler
    container_name: handlers
    command: bash -c "python src/mqhandler/infrastructure/mq/health_check.py && python src/mqhandler/infrastructure/mq/run.py"
    env_file:
      - .env
    depends_on:
      - mq

  bot:
    image: sergienkoandrew/mqhandler-bot
    container_name: bot
    command: bash -c "python src/mqhandlerbot/health_check.py && python src/mqhandlerbot/main.py"
    env_file:
      - .env
    depends_on:
      - handler
      - mq

  mq:
    image: rabbitmq:3-management
    container_name: message_queue
    ports:
      - "${AMQP_PORT}:${AMQP_PORT}"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${AMQP_VHOST}
