[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tools.isort]
profile = "black"

[tool.black]
line-length = 79
target-version = ['py310']

[tool.pytest_env]
TEST_ENV = "TEST_VALUE"
