[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
target-version = ['py310']

[tool.pytest_env]
TEST_ENV = "TEST_VALUE"
FILE_PATH = "test_message.json"
